### PR TITLE
Add threading to the client

### PR DESCRIPTION
**Pull request by bobvanluijt**
Threading for the Python client.

What needs to happen is:

1. Add tests
2. Add batching for manual batching (i.e., behavior when `client.batch.configure()` is not set or when `client.batch.configure(batch_size=None)`
3. Validate if documentation is correct

The documentation on the website (weaviate.io) doesn't have to change because it does not impact the user.

### CODE REVIEW

**Comment by StefanBogdan** [comment]
Hi @bobvanluijt, I am not sure this will work as intended.

1. Here we set `threads` but you create coroutines.
2. The `requests` library is not async compatible, so all the parallelism we want will actually result in a sequential execution.

We can introduce this functionality by using either `threads` or `processes`.

**Comment by bobvanluijt** [comment]
It uses this approach: https://stackoverflow.com/a/22414756/1501285

1. An array of batches is created.
2. A single batch is fired and awaited.

On the same setup as Weaviate’s ANN benchmarks this results in ≈ 2x improvement.

Probably more can be done but it's a start.

PS:
Most importantly, it doesn't break the UX of current implementations.

**Comment by StefanBogdan** [comment]
I have created something similar that does not have any breaking changes in the client, please see: https://github.com/semi-technologies/weaviate-python-client/pull/138

Lets keep this PR open until we decide which one is going to be merged.

**Comment by bobvanluijt** [comment]
I'm agnostic on the _how_ as long as it has a great UX 👍

**Comment by StefanBogdan** [comment]
This is fixed in another PR https://github.com/semi-technologies/weaviate-python-client/pull/138, closing

**Pull request closed without merging**
